// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	CROSSSITEREQUESTBLOCKED ErrorCode = "CROSS_SITE_REQUEST_BLOCKED"
	INTERNAL                ErrorCode = "INTERNAL"
	INVALIDCREDENTIALS      ErrorCode = "INVALID_CREDENTIALS"
	INVALIDJSONBODY         ErrorCode = "INVALID_JSON_BODY"
	TOOMANYATTEMPTS         ErrorCode = "TOO_MANY_ATTEMPTS"
	UNAUTHORIZED            ErrorCode = "UNAUTHORIZED"
	VALIDATION              ErrorCode = "VALIDATION"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case CROSSSITEREQUESTBLOCKED:
		return true
	case INTERNAL:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDJSONBODY:
		return true
	case TOOMANYATTEMPTS:
		return true
	case UNAUTHORIZED:
		return true
	case VALIDATION:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Locale.
const (
	EnGB Locale = "en-GB"
	IdID Locale = "id-ID"
)

// Valid indicates whether the value is a known member of the Locale enum.
func (e Locale) Valid() bool {
	switch e {
	case EnGB:
		return true
	case IdID:
		return true
	default:
		return false
	}
}

// Defines values for MeAllowanceMode.
const (
	Adaptive MeAllowanceMode = "adaptive"
	Flat     MeAllowanceMode = "flat"
)

// Valid indicates whether the value is a known member of the MeAllowanceMode enum.
func (e MeAllowanceMode) Valid() bool {
	switch e {
	case Adaptive:
		return true
	case Flat:
		return true
	default:
		return false
	}
}

// AuthMethods defines model for AuthMethods.
type AuthMethods struct {
	// Google Always false in MVP; planned, not built (PRD §4.1).
	Google bool `json:"google"`

	// Local Email + password. The only method in MVP.
	Local bool `json:"local"`
}

// Error The one error envelope both backends emit (PRD N7), identical in shape
// to Balances ADR-0027. It carries **codes, not messages** — the frontend
// looks `code` up in its i18n catalogue and interpolates `args`. There is
// deliberately no `message` field: shipping English beside the code invites
// copy drift between the two.
type Error struct {
	// Args Interpolation values for the catalogue string, keyed to its
	// placeholders. JSON primitives only, never nested — the frontend
	// passes them straight to `t(key, args)`.
	Args *map[string]interface{} `json:"args,omitempty"`

	// Code `SCREAMING_SNAKE_CASE`, matching Balances ADR-0027 where a code means the
	// same thing. Closed set, extended as endpoints land; an unknown code
	// falls back to the client's generic string.
	//
	// `VALIDATION` carries `{field, rule}` in `args` and reports only the
	// first failing field, as in Balances.
	Code ErrorCode `json:"code"`
}

// ErrorCode `SCREAMING_SNAKE_CASE`, matching Balances ADR-0027 where a code means the
// same thing. Closed set, extended as endpoints land; an unknown code
// falls back to the client's generic string.
//
// `VALIDATION` carries `{field, rule}` in `args` and reports only the
// first failing field, as in Balances.
type ErrorCode string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`

	// Version Build identifier of the running instance.
	//
	// Example: 0.1.0-a1b2c3d
	Version *string `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LocalLoginRequest defines model for LocalLoginRequest.
type LocalLoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Locale Both locales are real from day one (PRD N12a); the frontend owns every
// user-facing string.
type Locale string

// Me The User's own fields (PRD S4) plus the Household settings the client
// needs to render anything (PRD S3). One call, because every screen needs
// both and they change rarely.
type Me struct {
	// AllowanceMode Default adaptive.
	AllowanceMode MeAllowanceMode `json:"allowance_mode"`

	// DayStartsAt Local time a Period Day rolls over, `HH:MM`. Default 04:00. The
	// server does all Period Day arithmetic; the client never derives it
	// (BOOTSTRAP.md §4).
	//
	//
	// Example: 04:00
	DayStartsAt string `json:"day_starts_at"`
	DisplayName string `json:"display_name"`
	Email       string `json:"email"`

	// ExpectedMonthlyIncome Decimal serialised as a string (PRD N2). Nullable — the Household
	// may never supply one.
	//
	//
	// Example: 25000000.0000
	ExpectedMonthlyIncome *string `json:"expected_monthly_income,omitempty"`
	HouseholdDisplayName  string  `json:"household_display_name"`

	// HouseholdId A User belongs to exactly one Household and the binding is
	// irreversible (PRD S1).
	HouseholdId openapi_types.UUID `json:"household_id"`

	// Id UUIDv7.
	Id openapi_types.UUID `json:"id"`

	// Locale Both locales are real from day one (PRD N12a); the frontend owns every
	// user-facing string.
	Locale Locale `json:"locale"`

	// PeriodStartDay Day of month a Budget Period opens. Default 1.
	PeriodStartDay int `json:"period_start_day"`

	// ReportingCurrency ISO 4217 code. Default IDR.
	//
	// Example: IDR
	ReportingCurrency string `json:"reporting_currency"`

	// TimeZone IANA time zone identifier.
	//
	// Example: Asia/Jakarta
	TimeZone string `json:"time_zone"`
}

// MeAllowanceMode Default adaptive.
type MeAllowanceMode string

// BadRequest The one error envelope both backends emit (PRD N7), identical in shape
// to Balances ADR-0027. It carries **codes, not messages** — the frontend
// looks `code` up in its i18n catalogue and interpolates `args`. There is
// deliberately no `message` field: shipping English beside the code invites
// copy drift between the two.
type BadRequest = Error

// InternalError The one error envelope both backends emit (PRD N7), identical in shape
// to Balances ADR-0027. It carries **codes, not messages** — the frontend
// looks `code` up in its i18n catalogue and interpolates `args`. There is
// deliberately no `message` field: shipping English beside the code invites
// copy drift between the two.
type InternalError = Error

// TooManyRequests The one error envelope both backends emit (PRD N7), identical in shape
// to Balances ADR-0027. It carries **codes, not messages** — the frontend
// looks `code` up in its i18n catalogue and interpolates `args`. There is
// deliberately no `message` field: shipping English beside the code invites
// copy drift between the two.
type TooManyRequests = Error

// Unauthorized The one error envelope both backends emit (PRD N7), identical in shape
// to Balances ADR-0027. It carries **codes, not messages** — the frontend
// looks `code` up in its i18n catalogue and interpolates `args`. There is
// deliberately no `message` field: shipping English beside the code invites
// copy drift between the two.
type Unauthorized = Error

// LocalLoginJSONRequestBody defines body for LocalLogin for application/json ContentType.
type LocalLoginJSONRequestBody = LocalLoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// LocalLogin Exchange email and password for a server-side session.
	// (POST /auth/local/login)
	LocalLogin(w http.ResponseWriter, r *http.Request)
	// Logout Destroy the current server-side session.
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// GetAuthMethods Which identity providers this instance has enabled.
	// (GET /auth/methods)
	GetAuthMethods(w http.ResponseWriter, r *http.Request)
	// GetHealth Liveness and readiness of this instance.
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetMe The signed-in User and their Household's settings.
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// LocalLogin Exchange email and password for a server-side session.
// (POST /auth/local/login)
func (_ Unimplemented) LocalLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Destroy the current server-side session.
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAuthMethods Which identity providers this instance has enabled.
// (GET /auth/methods)
func (_ Unimplemented) GetAuthMethods(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealth Liveness and readiness of this instance.
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe The signed-in User and their Household's settings.
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LocalLogin operation middleware
func (siw *ServerInterfaceWrapper) LocalLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LocalLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMethods operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMethods(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMethods(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/methods", wrapper.GetAuthMethods)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/local/login", wrapper.LocalLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})

	return r
}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsJSONResponse struct {
	Body Error

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedJSONResponse Error

type LocalLoginRequestObject struct {
	Body *LocalLoginJSONRequestBody
}

type LocalLoginResponseObject interface {
	VisitLocalLoginResponse(w http.ResponseWriter) error
}

type LocalLogin204ResponseHeaders struct {
	SetCookie *string
}

type LocalLogin204Response struct {
	Headers LocalLogin204ResponseHeaders
}

func (response LocalLogin204Response) VisitLocalLoginResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type LocalLogin400JSONResponse struct{ BadRequestJSONResponse }

func (response LocalLogin400JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type LocalLogin401JSONResponse struct{ UnauthorizedJSONResponse }

func (response LocalLogin401JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LocalLogin429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response LocalLogin429JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LocalLogin500JSONResponse struct{ InternalErrorJSONResponse }

func (response LocalLogin500JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie *string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type Logout500JSONResponse struct{ InternalErrorJSONResponse }

func (response Logout500JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthMethodsRequestObject struct {
}

type GetAuthMethodsResponseObject interface {
	VisitGetAuthMethodsResponse(w http.ResponseWriter) error
}

type GetAuthMethods200JSONResponse AuthMethods

func (response GetAuthMethods200JSONResponse) VisitGetAuthMethodsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse Health

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetMe500JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// LocalLogin Exchange email and password for a server-side session.
	// (POST /auth/local/login)
	LocalLogin(ctx context.Context, request LocalLoginRequestObject) (LocalLoginResponseObject, error)
	// Logout Destroy the current server-side session.
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// GetAuthMethods Which identity providers this instance has enabled.
	// (GET /auth/methods)
	GetAuthMethods(ctx context.Context, request GetAuthMethodsRequestObject) (GetAuthMethodsResponseObject, error)
	// GetHealth Liveness and readiness of this instance.
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetMe The signed-in User and their Household's settings.
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// LocalLogin operation middleware
func (sh *strictHandler) LocalLogin(w http.ResponseWriter, r *http.Request) {
	var request LocalLoginRequestObject

	var body LocalLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LocalLogin(ctx, request.(LocalLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LocalLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LocalLoginResponseObject); ok {
		if err := validResponse.VisitLocalLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthMethods operation middleware
func (sh *strictHandler) GetAuthMethods(w http.ResponseWriter, r *http.Request) {
	var request GetAuthMethodsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthMethods(ctx, request.(GetAuthMethodsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthMethods")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthMethodsResponseObject); ok {
		if err := validResponse.VisitGetAuthMethodsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFnrcts4ln6VU9yp6jhL0bKTbE+ra3/Il0o07dtazmzNRl4JIg9FjMEDDgDa5vS6ah5i3mHfYx9lnmTr",
	"AJREWXLSt0x+pESaAM7l+84NP0apLitNSM5Ggx8jg7bSZNE/HInsGv9So3X8lGpySP6nqColU+Gkpv0/",
	"W038zqYFloJ//c5gHg2if9lfb70f/mr3T43RJnp6eoqjDG1qZMWbRIPoXKhcmxIzmOusiUEbEJBLVBm4",
	"QjjIhVSYwb1QMvMHJ9FTHI3IoSGhwrZfXciPhI8Vpg4zsGju0fSszNDLVhv0Et1ofS6oae1mv75MZ3oh",
	"CeYivdN5Dq8qNL3RFQjKgH9iKaTaS2B2jc40vWHu0MwgFcZItOAKhAchHUiakMVUU2YTOAp7xUB4j+yG",
	"QpgMlE7vdO3gH3/7e/cVSAsCLKq8V2jrJpRr7RY1JROK4qhAkaHxVugIwI+bSozD2eB0kGeOuTYIhtdI",
	"WiRR3DGTayqMBpEkhwv0NnmKo48kaldoI/+K2dc3+oUOSASL1kpNHq+pwQzJSaFswGymgbQDFozfp8Ix",
	"Rp6WunizDGtXnKMrdOYfRZZJPkOoK6MrNE4yFXOhLMZR1Xn1Y7TQeqFw25ZD9SAaC34NSILzP159D5US",
	"RJjFXqB5LZWDV1fXJ/B///s2Odhj+7ZWnWutUBBDWelUqO39TxlS8K9QCWsftMkSuCkQNKkGSq9Ie+iu",
	"TZ/iyOBfamnYSZ/aE+KlKrerBXr+Z0wdC7Fi9mctsylhkAcBeS0g3aPSFcJcu8ITBRlqWMrWBhff7sUg",
	"s+AixdLbQlQ4IafhSChBKVoYnlz3+v3DbxMYuRV/Xr9OdYY2WLVEa8UC7evXniPMrdx4FGYTUlrfWZjx",
	"5zOoKz5EOgvy4PcEqXBC6UWNnrUMa1NpJRxamAmzsDNvYYMg7YQyVHKORjhUDZCGWXvsLATLAdhCVpWk",
	"BZzSQklbwBx9kGJ5+HiQdC8d2gmlumogMzJnvrkHRPIfuQcdyLsJN5bkZT84U2+5YbTSRGpivtRoIdcm",
	"iLJS2jojaRHDHTaYgdNsmAlVSqRYaMXhI4E/jC8voDKylE7eo/VoW8YnQssBedvmDNAQ5Eo+RMhF4Xj/",
	"mXt1h00MrNHeLOi6hTs21U8KD8f84XNg+9Uvwvm43XvTXLPx8fXp8Hx08X46vhj+cDo9Ho5PZzGUwqUF",
	"O3QLi/DgYSGCX0sU5LWdkBUlO5wjJxwrbX2+cjHgI1sGMxAWkLJKS3IWlKDsexAENd2RfiC/3YRyoZT1",
	"fGGjeZ8pieS+sbBAQiPT1nXJhCY0++PwbHQyvBldXqzzy+xHD8oYTK3wacaoD4j2SDdYaeOCM4PcuTQ2",
	"pHrWt10rLK9bKh/chVSXbOf1oVEcjS7845TBMj26PPlT593x9enJ6cXNaHg2juLo5vJyej68+NN0eHNz",
	"en51w+8+Xgw/3ny4vB791+lJFEfH15fj8XQ8ujmdXp/+x8fT8c306Ozy+Af/x9HFzen1xfCs4+JgCnbx",
	"BxTKFT8zmFsnXO1/LVXTdxETamFEhtnOg+7RWKlpG0lHtVRZG9FyiQZ07v1naiI2rCTr2JgcofFRlBWn",
	"kaifHCT9njiYH6ZvsmjrvGcIbwXehfEzjuq+LOlUjz/DFr5m4R9cEAoXDdo3cVSKxzOkBVv3zWF/h0mW",
	"OWlj9erlxgZv+9/9WxyVkpYvDr6k8lKK1X4vKr+D3UecfHy+QwvC1zZCcbAqIRONT1chGR0cir3vNyIZ",
	"6AeywLGumVBt0fRykbIfV/TrMAKp9/4oiiOZ9UYnO2Fzjr8gnX60aL6xLEmgpQ3Sjt/uQaXqUEl+0LX1",
	"IRssOidpYTtRY0KEGCo8wzHIgKDGh6h2pzd7CVwSJwalYphjKmqLQWuwqUEk8DtMyOdxDiCuwAbSQtAC",
	"wQiDqtmZuJTSDwz3abkz7p5gLmrlQGSi4uySdKy5fBfFUa6E22nPTDRT64Rxdirc9vYeEOBkyYH6Co3U",
	"GZyIBozm8Krv0cQw+/BhcH4+S2ApS//toN/3aX9CodOATDNwlOruIYx0RYlOpt93TN3mxQyNz5XSTejV",
	"0eXlzfjmeniVlBkXfXstatbs5xM9uJ1Dw4L/96tP/YPbT/3ed7f/c/ip33tzuzf41O+9C69+F+0yhbSV",
	"Es2UROkN3aHb4bt3X2Bb/Bnib3/a9mHTUpMrVDOVlOpyp3dTWQoFFo0UStqQ/ETLnZZzh3sJXNRKibnC",
	"VSGxgvOEStG0RrV1VSlP1+cGPHzX9/8S/i+KI2r3W9ZGWyoUy/2nv9Js641ktqMd8NyFOSrtGakBH0Xq",
	"ghIdzraEgrmkzCcJOyFpDPosw3YJND1okbNyUV3LbJeHdsny8ePo5P7b5KcsV6s4+rkKrI22HPk9KwIR",
	"p5lodiCBw2wOHjAg4KjOFuiWbNIVkl3z7yAJyUKWHAcOf+99EB7WHlg1oHEUShlJi2laG4OU7jh/NL6E",
	"t4cH3/ryan3U6OR6Mw+PTq6fpboNBLzZYSyOLtO/atqB/9HwYhiiD/+9UxRsHjq0Uuz/QdwJ48QXc7/3",
	"2Abq4hVTN7C8cmNXxBeRv9OMOzz7POTGz0P8dl7mnhvT2kjXjBk6bdEVmvdjre+kN51ki6XhMY4CHSOR",
	"Ky3ctP14bRxRyR+wCdMBSbnetn0nIVboWdVzRrBE2jQwvBr5ynmcijz3Hzms4BCex+qDg70BFL6ohLTA",
	"9M5TtTNUkJpCDf2Pv/19Qki6XhTM88ro+9D3+XpdOG04W0oCkRptLbzXMfygneI3lMFNU+HYi59MaC17",
	"rmsvexw6x3CeSFOsfBHpl4Y0nemSdzdodW1S9I1FGC2xZt8FuQ3CRg8r5hbJAXcyIbIomSJZ74/WA8P3",
	"V2e9N0m/x1pGcVQbFQ2iwrnKDvb3Hx4ekgXViTaL/Xat3ReLSvGSpHClChRxAejem1Gneg6FL3/DQUBU",
	"MhpEvPJNyIaFh8o+23vfo3lfcWnLLyttdyT8C1GirUSKGcz8gtlmmWc1TzZrVxuEWdg3zD/2X89AWqhq",
	"rmQmFCq0e9wY1DBgLglsnaZoQ321HNmuui4BhbbOG2s5n4IA6u1C4N3ewE8RTrzrZiCcM3JeO+SixLnq",
	"klQzi2E2ZvbgLJ7QbCxKHEuH/34mHsNowo9sWXQsK9esEmhbjeSa2WnhQboCZu9Pb2C/xJnX5NTDph2f",
	"AnPXL172oT6mxCBCBvPrSXfGbDE8GE2LCS0rcr/aoKtN6ITBN8KzHU3gLF4lvLa+qkRjJ8QvCmF9XZpq",
	"6xjZxH02bR4N+CitszF7k1C6As16wkLahJ2cLHkjriY93C3zRtfk2jaWy1TPp1EWDTp9UxTiLVp3pLPm",
	"NxtnbjdmT5uhnSsV/6JzCXDYf7ujqOiMNLMEhs9wxliw6JLNCfAYXW8da7d7jM09EhgusWihQgPPkbtz",
	"KLzKWKzY237/JZOsVNzvXHL4JQdfXrIxa+ZFh999edHzi4GnOHr3U+TbvOLoZrJo8Ok2jmxdlsI0PJh9",
	"bHshz5twBbAkRu7vU7qXFq212YpO8GjvU8RaRbd8xDLcLXTtXo50V0bfywxNTyxIWyfTQCqZYVlphuvA",
	"d3O+mnSev7p2IJZH+6uDCbWxLAxRBYWpbRzCZBtCUoXCl+sCrBMKlzALNXkhLDg9IVthKoXqpcLiMjLW",
	"yiVwjfe6zZOyjQutBEY/fGM5HyH/dTcpvQ1+Cim6GJa8q3VG80xzGWlaqb02mP0qdvAsr5LtLp9nwS9F",
	"2QpXJ0GRoIKvy9zPRVK5vuFYoNutYGWwxx9DqimXC7C1yUWKA3/u+GoIBkVmoXs7RBm2sPA5eULtoIAN",
	"bgtOOsvZYns10V7McBGiuNWHkb+qWCVq2Q5Q/TJNGD5PBcEcgaNjO5nx95IhBTBQkcTcw/y9T+SghEPj",
	"O6hVEtfUzYlO611ge4+uex+0Bbr+b5YKusfsuN9if3ilMIOqZblNPht9/rOQadH2F65ZrwJXSLsaOXqy",
	"tjt3AWMb67BsIVOsJqgtWLas1M5Yv6KB2hNesM1KHZ/ozL0HIYc+ZyETTsw5BEnLkE0LVjYJ8f7NP0G+",
	"IWTI7Qa3TyxDTV0pPuPBM3mPhNa2w3mRSf+k800Xvui2Ejsu27bZ6vYgTPk5M4Dg62CO6iEH5LUKTI5X",
	"1lyGvcrouScmKC18yfG2f9DeeUwiJrvnl1/dzgsn0QscO8eviZxzfAk1neTgb4+TX1xx/OqY7sWRC8Ks",
	"JynU122WkmY9FPrGrka5u6L7Jpa2+ulPt0+ML58prP8gNG773GM93a722xpZLMmluoB8lh7q4NIEgmnW",
	"xei6cW/B+RTvHsnis3vspXssbDdJnV298k+3T/8/AA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
