// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	CROSSSITEREQUESTBLOCKED ErrorCode = "CROSS_SITE_REQUEST_BLOCKED"
	INTERNAL                ErrorCode = "INTERNAL"
	INVALIDCREDENTIALS      ErrorCode = "INVALID_CREDENTIALS"
	INVALIDJSONBODY         ErrorCode = "INVALID_JSON_BODY"
	TOOMANYATTEMPTS         ErrorCode = "TOO_MANY_ATTEMPTS"
	UNAUTHORIZED            ErrorCode = "UNAUTHORIZED"
	VALIDATION              ErrorCode = "VALIDATION"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case CROSSSITEREQUESTBLOCKED:
		return true
	case INTERNAL:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDJSONBODY:
		return true
	case TOOMANYATTEMPTS:
		return true
	case UNAUTHORIZED:
		return true
	case VALIDATION:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Degraded HealthStatus = "degraded"
	Ok       HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for Locale.
const (
	EnGB Locale = "en-GB"
	IdID Locale = "id-ID"
)

// Valid indicates whether the value is a known member of the Locale enum.
func (e Locale) Valid() bool {
	switch e {
	case EnGB:
		return true
	case IdID:
		return true
	default:
		return false
	}
}

// Defines values for MeAllowanceMode.
const (
	Adaptive MeAllowanceMode = "adaptive"
	Flat     MeAllowanceMode = "flat"
)

// Valid indicates whether the value is a known member of the MeAllowanceMode enum.
func (e MeAllowanceMode) Valid() bool {
	switch e {
	case Adaptive:
		return true
	case Flat:
		return true
	default:
		return false
	}
}

// AuthMethods defines model for AuthMethods.
type AuthMethods struct {
	// Google Always false in MVP; planned, not built (PRD §4.1).
	Google bool `json:"google"`

	// Local Email + password. The only method in MVP.
	Local bool `json:"local"`
}

// Error The one error envelope both backends emit (PRD N7), identical in shape
// to Balances ADR-0027. It carries **codes, not messages** — the frontend
// looks `code` up in its i18n catalogue and interpolates `args`. There is
// deliberately no `message` field: shipping English beside the code invites
// copy drift between the two.
type Error struct {
	// Args Interpolation values for the catalogue string, keyed to its
	// placeholders. JSON primitives only, never nested — the frontend
	// passes them straight to `t(key, args)`.
	Args *map[string]interface{} `json:"args,omitempty"`

	// Code `SCREAMING_SNAKE_CASE`, matching Balances ADR-0027 where a code means the
	// same thing. Closed set, extended as endpoints land; an unknown code
	// falls back to the client's generic string.
	//
	// `VALIDATION` carries `{field, rule}` in `args` and reports only the
	// first failing field, as in Balances.
	Code ErrorCode `json:"code"`
}

// ErrorCode `SCREAMING_SNAKE_CASE`, matching Balances ADR-0027 where a code means the
// same thing. Closed set, extended as endpoints land; an unknown code
// falls back to the client's generic string.
//
// `VALIDATION` carries `{field, rule}` in `args` and reports only the
// first failing field, as in Balances.
type ErrorCode string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`

	// Version Build identifier of the running instance.
	//
	// Example: 0.1.0-a1b2c3d
	Version *string `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// LocalLoginRequest defines model for LocalLoginRequest.
type LocalLoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Locale Both locales are real from day one (PRD N12a); the frontend owns every
// user-facing string.
type Locale string

// Me The User's own fields (PRD S4) plus the Household settings the client
// needs to render anything (PRD S3). One call, because every screen needs
// both and they change rarely.
type Me struct {
	// AllowanceMode Default adaptive.
	AllowanceMode MeAllowanceMode `json:"allowance_mode"`

	// DayStartsAt Local time a Period Day rolls over, `HH:MM`. Default 04:00. The
	// server does all Period Day arithmetic; the client never derives it
	// (BOOTSTRAP.md §4).
	//
	//
	// Example: 04:00
	DayStartsAt string              `json:"day_starts_at"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`

	// ExpectedMonthlyIncome Decimal serialised as a string (PRD N2). Nullable — the Household
	// may never supply one.
	//
	//
	// Example: 25000000.0000
	ExpectedMonthlyIncome *string `json:"expected_monthly_income,omitempty"`
	HouseholdDisplayName  string  `json:"household_display_name"`

	// HouseholdId A User belongs to exactly one Household and the binding is
	// irreversible (PRD S1).
	HouseholdId openapi_types.UUID `json:"household_id"`

	// Id UUIDv7.
	Id openapi_types.UUID `json:"id"`

	// Locale Both locales are real from day one (PRD N12a); the frontend owns every
	// user-facing string.
	Locale Locale `json:"locale"`

	// PeriodStartDay Day of month a Budget Period opens. Default 1.
	PeriodStartDay int `json:"period_start_day"`

	// ReportingCurrency ISO 4217 code. Default IDR.
	//
	// Example: IDR
	ReportingCurrency string `json:"reporting_currency"`

	// TimeZone IANA time zone identifier.
	//
	// Example: Asia/Jakarta
	TimeZone string `json:"time_zone"`
}

// MeAllowanceMode Default adaptive.
type MeAllowanceMode string

// BadRequest The one error envelope both backends emit (PRD N7), identical in shape
// to Balances ADR-0027. It carries **codes, not messages** — the frontend
// looks `code` up in its i18n catalogue and interpolates `args`. There is
// deliberately no `message` field: shipping English beside the code invites
// copy drift between the two.
type BadRequest = Error

// InternalError The one error envelope both backends emit (PRD N7), identical in shape
// to Balances ADR-0027. It carries **codes, not messages** — the frontend
// looks `code` up in its i18n catalogue and interpolates `args`. There is
// deliberately no `message` field: shipping English beside the code invites
// copy drift between the two.
type InternalError = Error

// TooManyRequests The one error envelope both backends emit (PRD N7), identical in shape
// to Balances ADR-0027. It carries **codes, not messages** — the frontend
// looks `code` up in its i18n catalogue and interpolates `args`. There is
// deliberately no `message` field: shipping English beside the code invites
// copy drift between the two.
type TooManyRequests = Error

// Unauthorized The one error envelope both backends emit (PRD N7), identical in shape
// to Balances ADR-0027. It carries **codes, not messages** — the frontend
// looks `code` up in its i18n catalogue and interpolates `args`. There is
// deliberately no `message` field: shipping English beside the code invites
// copy drift between the two.
type Unauthorized = Error

// LocalLoginJSONRequestBody defines body for LocalLogin for application/json ContentType.
type LocalLoginJSONRequestBody = LocalLoginRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// LocalLogin Exchange email and password for a server-side session.
	// (POST /auth/local/login)
	LocalLogin(w http.ResponseWriter, r *http.Request)
	// Logout Destroy the current server-side session.
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// GetAuthMethods Which identity providers this instance has enabled.
	// (GET /auth/methods)
	GetAuthMethods(w http.ResponseWriter, r *http.Request)
	// GetHealth Liveness and readiness of this instance.
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// GetMe The signed-in User and their Household's settings.
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// LocalLogin Exchange email and password for a server-side session.
// (POST /auth/local/login)
func (_ Unimplemented) LocalLogin(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Destroy the current server-side session.
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetAuthMethods Which identity providers this instance has enabled.
// (GET /auth/methods)
func (_ Unimplemented) GetAuthMethods(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealth Liveness and readiness of this instance.
// (GET /health)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe The signed-in User and their Household's settings.
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LocalLogin operation middleware
func (siw *ServerInterfaceWrapper) LocalLogin(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LocalLogin(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthMethods operation middleware
func (siw *ServerInterfaceWrapper) GetAuthMethods(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthMethods(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/methods", wrapper.GetAuthMethods)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/local/login", wrapper.LocalLogin)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})

	return r
}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsJSONResponse struct {
	Body Error

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedJSONResponse Error

type LocalLoginRequestObject struct {
	Body *LocalLoginJSONRequestBody
}

type LocalLoginResponseObject interface {
	VisitLocalLoginResponse(w http.ResponseWriter) error
}

type LocalLogin204ResponseHeaders struct {
	SetCookie *string
}

type LocalLogin204Response struct {
	Headers LocalLogin204ResponseHeaders
}

func (response LocalLogin204Response) VisitLocalLoginResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type LocalLogin400JSONResponse struct{ BadRequestJSONResponse }

func (response LocalLogin400JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type LocalLogin401JSONResponse struct{ UnauthorizedJSONResponse }

func (response LocalLogin401JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type LocalLogin429JSONResponse struct{ TooManyRequestsJSONResponse }

func (response LocalLogin429JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LocalLogin500JSONResponse struct{ InternalErrorJSONResponse }

func (response LocalLogin500JSONResponse) VisitLocalLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie *string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	if response.Headers.SetCookie != nil {
		w.Header().Set("Set-Cookie", fmt.Sprint(*response.Headers.SetCookie))
	}
	w.WriteHeader(204)
	return nil
}

type Logout500JSONResponse struct{ InternalErrorJSONResponse }

func (response Logout500JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetAuthMethodsRequestObject struct {
}

type GetAuthMethodsResponseObject interface {
	VisitGetAuthMethodsResponse(w http.ResponseWriter) error
}

type GetAuthMethods200JSONResponse AuthMethods

func (response GetAuthMethods200JSONResponse) VisitGetAuthMethodsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse Health

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealth503JSONResponse Health

func (response GetHealth503JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMe401JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetMe500JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// LocalLogin Exchange email and password for a server-side session.
	// (POST /auth/local/login)
	LocalLogin(ctx context.Context, request LocalLoginRequestObject) (LocalLoginResponseObject, error)
	// Logout Destroy the current server-side session.
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// GetAuthMethods Which identity providers this instance has enabled.
	// (GET /auth/methods)
	GetAuthMethods(ctx context.Context, request GetAuthMethodsRequestObject) (GetAuthMethodsResponseObject, error)
	// GetHealth Liveness and readiness of this instance.
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// GetMe The signed-in User and their Household's settings.
	// (GET /me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// LocalLogin operation middleware
func (sh *strictHandler) LocalLogin(w http.ResponseWriter, r *http.Request) {
	var request LocalLoginRequestObject

	var body LocalLoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.LocalLogin(ctx, request.(LocalLoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LocalLogin")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LocalLoginResponseObject); ok {
		if err := validResponse.VisitLocalLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAuthMethods operation middleware
func (sh *strictHandler) GetAuthMethods(w http.ResponseWriter, r *http.Request) {
	var request GetAuthMethodsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetAuthMethods(ctx, request.(GetAuthMethodsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAuthMethods")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetAuthMethodsResponseObject); ok {
		if err := validResponse.VisitGetAuthMethodsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
