package dev.kerti.afloat.auth

import dev.kerti.afloat.testsupport.verifyUnderPermit
import io.kotest.assertions.withClue
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.shouldNotBe
import io.kotest.matchers.string.shouldStartWith
import org.springframework.security.crypto.argon2.Argon2PasswordEncoder
import java.time.Duration
import java.util.Base64

// #14 tests 1-6. The cost parameters travel inside every PHC string, so these
// assert the encoding itself rather than the constants: a hash written by
// either backend must verify in the other (BOOTSTRAP.md §5.1).
class PasswordServiceSpec : StringSpec({

    val service = PasswordService(Duration.ofSeconds(30))

    // BOOTSTRAP §5.1's parameters, spelled the way the PHC string spells them.
    val mandatedPrefix = "\$argon2id\$v=19\$m=19456,t=2,p=1\$"

    // hashIsAPhcStringWithTheMandatedParameters
    "hashes to a PHC string carrying the mandated parameters" {
        val phc = service.hash("correct horse battery staple")

        phc shouldStartWith mandatedPrefix

        // Raw standard base64, unpadded, on both segments: 16 salt bytes encode
        // to 22 characters and a 32-byte key to 43. A padded or URL-safe
        // alphabet here is exactly the difference Go would fail to read.
        val segments = phc.split("$")
        segments.size shouldBe 6
        val (salt, key) = segments[4] to segments[5]
        salt.length shouldBe 22
        key.length shouldBe 43
        // Unpadded and standard-alphabet: '=' would be padding and '-' or '_'
        // the URL-safe alphabet, either of which Go's RawStdEncoding rejects.
        (salt + key).none { it == '=' || it == '-' || it == '_' } shouldBe true
        Base64.getDecoder().decode(salt).size shouldBe 16
        Base64.getDecoder().decode(key).size shouldBe 32
    }

    // verifyUsesTheHashesOwnParametersNotTheCurrentConstants
    "verifies a hash recorded with different cost parameters" {
        // Retuning the constants must not lock out every existing user, so
        // verification reads m, t and p out of the string it was given.
        val cheaper = Argon2PasswordEncoder(16, 32, 1, 8192, 1)
        val phc = checkNotNull(cheaper.encode("correct horse battery staple"))

        phc shouldStartWith "\$argon2id\$v=19\$m=8192,t=1,p=1\$"
        service.verifyUnderPermit("correct horse battery staple", phc) shouldBe true
        service.verifyUnderPermit("not the password", phc) shouldBe false
    }

    // verifyReturnsFalseForAMalformedPhcString
    "returns false for a malformed PHC string rather than throwing" {
        // A corrupt credentials row must fail the login, not escape the
        // handler as a 500 that says the row exists. Go's
        // TestVerifyRejectsMalformedHashes covers the same shapes.
        listOf(
            "",
            "not a phc string at all",
            "\$argon2id\$v=19\$m=19456,t=2,p=1\$onlyfourparts",
            "\$argon2id\$v=19\$m=bad,t=2,p=1\$c2FsdA\$aGFzaA",
            "\$argon2id\$v=19\$m=19456,t=2,p=1\$!!!notbase64\$aGFzaA",
            "\$argon2id\$v=19\$m=19456,t=2,p=1\$c2FsdA",
        ).forEach { phc ->
            withClue("malformed PHC: '$phc'") {
                service.verifyUnderPermit("correct horse battery staple", phc) shouldBe false
            }
        }
    }

    // verifyReturnsFalseForAnUnsupportedAlgorithmOrVersion
    "returns false for an unsupported algorithm or version" {
        listOf(
            // argon2i and argon2d are not what we hash with.
            "\$argon2i\$v=19\$m=19456,t=2,p=1\$cAz2vjLpthahaEGhmk5fQQ\$xSslbUYj+Sx4LouRFXtaZmG8Wwy1Y5Iz6b3q2S76Da0",
            "\$argon2d\$v=19\$m=19456,t=2,p=1\$cAz2vjLpthahaEGhmk5fQQ\$xSslbUYj+Sx4LouRFXtaZmG8Wwy1Y5Iz6b3q2S76Da0",
            // Version 16 is the pre-standard Argon2; only 19 is accepted.
            "\$argon2id\$v=16\$m=19456,t=2,p=1\$cAz2vjLpthahaEGhmk5fQQ\$xSslbUYj+Sx4LouRFXtaZmG8Wwy1Y5Iz6b3q2S76Da0",
            "\$argon2id\$v=99\$m=19456,t=2,p=1\$c2FsdA\$aGFzaA",
            // bcrypt, from a household that migrated in from something else.
            "\$2a\$10\$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
        ).forEach { phc ->
            withClue("unsupported PHC: '$phc'") {
                service.verifyUnderPermit("correct horse battery staple", phc) shouldBe false
            }
        }
    }

    // verifyAcceptsAHashProducedByTheGoBackend
    "verifies hashes written by the Go backend" {
        // Generated by backend/internal/auth.HashPassword and pasted in with
        // their plaintexts. This is the floor for BOOTSTRAP §5.1's promise that
        // a hash written by either backend verifies in the other; the shared
        // fixture that makes it bidirectional is the parity issue after #14.
        val fromGo = mapOf(
            "correct horse battery staple" to
                "\$argon2id\$v=19\$m=19456,t=2,p=1\$cAz2vjLpthahaEGhmk5fQQ\$xSslbUYj+Sx4LouRFXtaZmG8Wwy1Y5Iz6b3q2S76Da0",
            // Non-ASCII-adjacent and longer than the ASCII case, so an encoding
            // difference in the plaintext shows up too.
            "kata sandi rahasia" to
                "\$argon2id\$v=19\$m=19456,t=2,p=1\$uGFbRRl5Ghp06HJEYomAkg\$rgbZlh4UoheVrrSOQCtZTKIBeyjxaH5TtiETW6j1ecU",
        )

        fromGo.forEach { (plaintext, phc) ->
            withClue("Go-written hash for '$plaintext'") {
                service.verifyUnderPermit(plaintext, phc) shouldBe true
                service.verifyUnderPermit("$plaintext ", phc) shouldBe false
            }
        }
    }

    // hashesAreSaltedIndependently
    "salts every hash independently" {
        val first = service.hash("correct horse battery staple")
        val second = service.hash("correct horse battery staple")

        first shouldNotBe second
        service.verifyUnderPermit("correct horse battery staple", first) shouldBe true
        service.verifyUnderPermit("correct horse battery staple", second) shouldBe true
    }

    // The dummy is what an unknown or dormant address is verified against, so
    // it has to be a hash the encoder will actually do the work on rather than
    // a constant it rejects early (see #14 test 23).
    "carries a dummy hash with the same parameters that nothing matches" {
        PasswordService.dummyHash shouldStartWith mandatedPrefix
        service.verifyUnderPermit("", PasswordService.dummyHash) shouldBe false
        service.verifyUnderPermit("correct horse battery staple", PasswordService.dummyHash) shouldBe false
    }
})
