#!/usr/bin/env bash
# Generate the Go backend's embedded goose migrations from the canonical
# Flyway-native ones.
#
# BOOTSTRAP.md §7: one directory cannot serve both tools. Flyway has no concept
# of goose's `-- +goose Up` / `-- +goose Down` markers and would execute an undo
# section as part of the migration; the two also disagree on file naming and
# keep independent ledgers. So the canonical files stay Flyway-native and up
# only, the undo files live outside Flyway's scanned path, and this script
# concatenates each pair into the file goose consumes:
#
#   db/migrations/V0001__baseline.sql   canonical, up only, what Flyway reads
#   db/undo/U0001__baseline.sql         down only, read by nothing but this
#   backend/internal/migrations/00001_baseline.sql   GENERATED, committed
#
# The output is committed and //go:embed-ed, so `make check` regenerates into a
# scratch directory and diffs. That catches both a stale generated file and a
# hand-edit of one.
#
# Usage: gen-goose-migrations.sh [output-dir]

set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

out_dir=${1:-backend/internal/migrations}

shopt -s nullglob
ups=(db/migrations/V*.sql)
shopt -u nullglob

if [ ${#ups[@]} -eq 0 ]; then
  echo "gen-goose-migrations: no migrations in db/migrations yet"
  exit 0
fi

mkdir -p "$out_dir"

for up in "${ups[@]}"; do
  base=$(basename "$up" .sql)
  version=$(sed -E 's/^V([0-9]+)__.*/\1/' <<<"$base")
  name=$(sed -E 's/^V[0-9]+__//' <<<"$base")

  if [ "$version" = "$base" ]; then
    echo "gen-goose-migrations: $up is not named V<digits>__<name>.sql" >&2
    exit 1
  fi

  down="db/undo/U${version}__${name}.sql"
  if [ ! -e "$down" ]; then
    echo "gen-goose-migrations: $up has no matching $down" >&2
    echo "  every canonical migration needs an undo file to generate a Down section." >&2
    exit 1
  fi

  # 10#$version strips the leading zeros without bash reading them as octal.
  out=$(printf '%s/%05d_%s.sql' "$out_dir" "$((10#$version))" "$name")

  {
    echo '-- Code generated by `make gen-goose-migrations`. DO NOT EDIT.'
    echo "-- Source: $up + $down"
    echo
    echo '-- +goose Up'
    cat "$up"
    echo
    echo '-- +goose Down'
    cat "$down"
  } >"$out"

  echo "ok $out"
done
