-- Code generated by `make gen-goose-migrations`. DO NOT EDIT.
-- Source: db/migrations/V0001__baseline.sql + db/undo/U0001__baseline.sql

-- +goose Up
-- Baseline: identity and authentication only (BOOTSTRAP.md §11 step 3).
-- Households, Users, credentials, sessions, invitations, login backoff. No
-- domain table (pockets, categories, budgets, expenses) lands until step 9.
--
-- Canonical and Flyway-native, up only. The goose file the Go binary embeds is
-- GENERATED from this plus db/undo/U0001__baseline.sql by
-- `make gen-goose-migrations` — never hand-edit backend/internal/migrations/.
--
-- Conventions this file is bound by (BOOTSTRAP.md §4):
--   * Primary keys are UUIDv7 and CLIENT-generated, so no column carries a
--     DEFAULT. A server-side gen_random_uuid() would be a v4 and would let a
--     missing client id pass silently.
--   * Money is DECIMAL(20,4).
--   * Soft delete on Household-scoped domain data. Instance-local auth state
--     (credentials, sessions, invitations, login_attempts) hard-deletes:
--     revocation IS the row delete.

-- ---------------------------------------------------------------------------
-- households
-- ---------------------------------------------------------------------------

CREATE TABLE households (
    id                      uuid PRIMARY KEY,
    display_name            text NOT NULL,
    -- PRD S3 defaults. They are declared here as well as in the application so
    -- a row inserted by a migration or a fixture gets the same Household as one
    -- inserted by onboarding.
    reporting_currency      text NOT NULL DEFAULT 'IDR',
    period_start_day        integer NOT NULL DEFAULT 1,
    -- Local wall-clock time a Period Day rolls over. Not timestamptz: it is a
    -- recurring time of day, resolved against each User's time_zone server-side
    -- (BOOTSTRAP.md §4 — the frontend never derives a Period Day).
    day_starts_at           time NOT NULL DEFAULT '04:00',
    -- Nullable: the Household may never supply one (PRD S5). The sole field
    -- anything outside Afloat may write (VISION.md §5).
    expected_monthly_income numeric(20,4),
    allowance_mode          text NOT NULL DEFAULT 'adaptive',
    created_at              timestamptz NOT NULL DEFAULT now(),
    updated_at              timestamptz NOT NULL DEFAULT now(),
    deleted_at              timestamptz,

    CONSTRAINT households_display_name_not_blank
        CHECK (btrim(display_name) <> ''),
    CONSTRAINT households_reporting_currency_iso4217
        CHECK (reporting_currency ~ '^[A-Z]{3}$'),
    -- 28 is the highest day that exists in every month; 29-31 would silently
    -- skip or clamp a Period in February.
    CONSTRAINT households_period_start_day_range
        CHECK (period_start_day BETWEEN 1 AND 28),
    CONSTRAINT households_allowance_mode_known
        CHECK (allowance_mode IN ('adaptive', 'flat')),
    -- Zero income is a real answer; negative is not.
    CONSTRAINT households_expected_monthly_income_non_negative
        CHECK (expected_monthly_income IS NULL OR expected_monthly_income >= 0)
);

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id            uuid PRIMARY KEY,
    -- A User belongs to exactly one Household and the binding is irreversible
    -- (PRD S1). All members have equal access — there is no role column, and
    -- deliberately no founder flag: PRD S2 has no permission tiers to hang on it.
    household_id  uuid NOT NULL REFERENCES households (id),
    email         text NOT NULL,
    display_name  text NOT NULL,
    locale        text NOT NULL DEFAULT 'en-GB',
    time_zone     text NOT NULL DEFAULT 'Asia/Jakarta',
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now(),
    deleted_at    timestamptz,

    CONSTRAINT users_display_name_not_blank
        CHECK (btrim(display_name) <> ''),
    -- Both locales are real from day one (PRD N12a). Widening this list is what
    -- adding a third language costs in the database.
    CONSTRAINT users_locale_known
        CHECK (locale IN ('en-GB', 'id-ID'))
);

-- Soft-delete-aware: a deleted User's address frees up for reuse, and two
-- deleted rows may share one. Email is the handle and the invitation-match key,
-- never the identity — users.id is.
CREATE UNIQUE INDEX users_email_idx
    ON users (lower(email))
    WHERE deleted_at IS NULL;

CREATE INDEX users_household_id_idx
    ON users (household_id)
    WHERE deleted_at IS NULL;

-- ---------------------------------------------------------------------------
-- credentials
-- ---------------------------------------------------------------------------

-- Users carry no credential column (BOOTSTRAP.md §5). Keeping the hash in its
-- own table is what makes Google OAuth later an additive provider rather than a
-- migration of the user model, and it makes "never serialise the secret"
-- structural rather than a per-column thing to remember.
--
-- A User with no row here is DORMANT: present, owns data, cannot yet
-- authenticate. That is a legitimate state (an invited member who has not set a
-- password), so "reachable" is an application invariant, not a CHECK.
CREATE TABLE credentials (
    user_id       uuid PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    -- Argon2id PHC string: $argon2id$v=19$m=19456,t=2,p=1$<salt>$<hash>.
    -- Salt and cost parameters travel inside it, so they retune with no
    -- migration and old hashes keep verifying against their own recorded cost
    -- (BOOTSTRAP.md §5.1).
    password_hash text NOT NULL,
    created_at    timestamptz NOT NULL DEFAULT now(),
    updated_at    timestamptz NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- sessions
-- ---------------------------------------------------------------------------

CREATE TABLE sessions (
    -- SHA-256 hex of the bearer token, never the token. The cookie carries the
    -- plaintext; a database leak yields nothing usable. Callers hash before
    -- every read and write.
    id           text PRIMARY KEY,
    user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- Read, not decorative: the absolute lifetime is checked against this, so a
    -- sliding window cannot keep a stolen cookie alive forever (BOOTSTRAP.md
    -- §5.1).
    created_at   timestamptz NOT NULL DEFAULT now(),
    expires_at   timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    user_agent   text
);

-- Supports revoke-all-for-user, which a password reset runs before minting the
-- replacement session.
CREATE INDEX sessions_user_id_idx ON sessions (user_id);

-- Supports the expired-session sweep.
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

-- ---------------------------------------------------------------------------
-- invitations
-- ---------------------------------------------------------------------------

-- A one-time link generated and shown in the UI; no email in MVP (PRD S2b).
-- The token model is nonetheless built as though email will deliver it later,
-- so nothing here assumes the founder reads it off a screen.
-- Both foreign keys CASCADE, like credentials and sessions and for the same
-- reason: this is instance-local auth state, so it should never be what blocks
-- a hard delete. Users are soft-deleted in normal operation, so a DELETE here is
-- always something deliberate — test teardown, or an erasure path if Q-14 is
-- ever answered — and a pending invitation is not worth wedging either.
CREATE TABLE invitations (
    id            uuid PRIMARY KEY,
    household_id  uuid NOT NULL REFERENCES households (id) ON DELETE CASCADE,
    -- Checked against the accepting identity, so forwarding the link to someone
    -- else does not let them join the Household.
    invited_email text NOT NULL,
    -- SHA-256 hex of the link token, for the same reason sessions.id is hashed.
    token_hash    text NOT NULL UNIQUE,
    created_by    uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at    timestamptz NOT NULL DEFAULT now(),
    expires_at    timestamptz NOT NULL,
    -- Non-null means consumed. Single-use.
    accepted_at   timestamptz
);

CREATE INDEX invitations_household_id_idx ON invitations (household_id);

-- ---------------------------------------------------------------------------
-- login_attempts
-- ---------------------------------------------------------------------------

-- Login backoff state, in the database rather than process memory
-- (BOOTSTRAP.md §5.1). With two backends an in-memory limiter is duplicated
-- stateful logic that contract conformance cannot check: Go and Kotlin could
-- disagree on the curve, on key normalisation or on eviction and every contract
-- test would still pass. A table is identical by construction and survives a
-- restart.
CREATE TABLE login_attempts (
    -- Namespaced key: 'ip:<addr>' or 'email:<lowercased address>'. One table for
    -- both, because the limiter treats them identically and a request checks the
    -- pair in a single read.
    key           text PRIMARY KEY,
    failure_count integer NOT NULL DEFAULT 0,
    -- Null means no active backoff. Backoff, never a hard lockout: a lockout on
    -- a self-hosted household app locks the household out of its own data.
    backoff_until timestamptz,
    updated_at    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT login_attempts_failure_count_non_negative
        CHECK (failure_count >= 0)
);

-- Supports the sweep that drops entries whose backoff has elapsed.
CREATE INDEX login_attempts_backoff_until_idx
    ON login_attempts (backoff_until)
    WHERE backoff_until IS NOT NULL;

-- +goose Down
-- Undo for V0001__baseline.sql.
--
-- NOT a Flyway location (BOOTSTRAP.md §7): Flyway's U__ undo migrations are a
-- paid feature, so these files sit outside the scanned path deliberately.
-- `flyway undo` is not available and is not meant to be. This file exists for
-- one reason — to be concatenated into the goose Down section by
-- `make gen-goose-migrations`.
--
-- Reverse order of creation, so foreign keys drop before their targets.

DROP TABLE IF EXISTS login_attempts;
DROP TABLE IF EXISTS invitations;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS credentials;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS households;
