// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearLoginAttempts = `-- name: ClearLoginAttempts :exec
DELETE FROM login_attempts WHERE key = ANY($1::text[])
`

func (q *Queries) ClearLoginAttempts(ctx context.Context, keys []string) error {
	_, err := q.db.Exec(ctx, clearLoginAttempts, keys)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at, user_agent)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, created_at, expires_at, last_seen_at, user_agent
`

type CreateSessionParams struct {
	ID        string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UserAgent *string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.UserAgent,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = $1
`

// Revoke every session a User holds. Run on a password change, inside the same
// transaction, so the change boots any other session before the new one is
// minted — the "reset because compromised" guarantee.
func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForUser, userID)
	return err
}

const getCredentialByUserID = `-- name: GetCredentialByUserID :one
SELECT user_id, password_hash, created_at, updated_at FROM credentials WHERE user_id = $1
`

// A User with no row here is DORMANT: present, owns data, cannot yet
// authenticate. A legitimate state, so this returning no rows is not an error.
func (q *Queries) GetCredentialByUserID(ctx context.Context, userID pgtype.UUID) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentialByUserID, userID)
	var i Credential
	err := row.Scan(
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHouseholdByID = `-- name: GetHouseholdByID :one
SELECT id, display_name, reporting_currency, period_start_day, day_starts_at, expected_monthly_income, allowance_mode, created_at, updated_at, deleted_at FROM households
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetHouseholdByID(ctx context.Context, id pgtype.UUID) (Household, error) {
	row := q.db.QueryRow(ctx, getHouseholdByID, id)
	var i Household
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.ReportingCurrency,
		&i.PeriodStartDay,
		&i.DayStartsAt,
		&i.ExpectedMonthlyIncome,
		&i.AllowanceMode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLiveSession = `-- name: GetLiveSession :one
SELECT id, user_id, created_at, expires_at, last_seen_at, user_agent FROM sessions
WHERE id = $1
  AND expires_at > now()
  AND created_at > now() - $2::interval
`

type GetLiveSessionParams struct {
	ID          string
	MaxLifetime pgtype.Interval
}

// sessions.id is the SHA-256 of the bearer token, never the token. Callers hash
// before every read and write.
//
// Both lifetimes are enforced here rather than in Go, so a caller cannot forget
// one: expires_at is the sliding window, created_at the absolute cap that stops
// a stolen cookie living forever on repeated use (BOOTSTRAP.md §5.1).
func (q *Queries) GetLiveSession(ctx context.Context, arg GetLiveSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, getLiveSession, arg.ID, arg.MaxLifetime)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.UserAgent,
	)
	return i, err
}

const getLoginBackoff = `-- name: GetLoginBackoff :one
SELECT coalesce(extract(epoch FROM (max(backoff_until) - now())), 0)::float8 AS remaining_seconds
FROM login_attempts
WHERE key = ANY($1::text[]) AND backoff_until > now()
`

// Login backoff lives in the database, not process memory, because there are
// two backends and an in-memory limiter would diverge where contract
// conformance cannot see it (BOOTSTRAP.md §5.1).
//
// Returns the remaining seconds, computed by the database's own clock, not a
// raw timestamp for Go to subtract against its own clock: any instant the
// database also evaluates (here, backoff_until > now()) comes from the
// database (BOOTSTRAP.md §5.1, #25). Coalesced to 0 so "no active backoff"
// (the aggregate over zero matching rows) is a plain zero, not a NULL scan.
func (q *Queries) GetLoginBackoff(ctx context.Context, keys []string) (float64, error) {
	row := q.db.QueryRow(ctx, getLoginBackoff, keys)
	var remaining_seconds float64
	err := row.Scan(&remaining_seconds)
	return remaining_seconds, err
}

const getUserByEmail = `-- name: GetUserByEmail :one

SELECT id, household_id, email, display_name, locale, time_zone, created_at, updated_at, deleted_at FROM users
WHERE lower(email) = lower($1) AND deleted_at IS NULL
`

// Authentication queries. Instance-local auth state hard-deletes: revocation IS
// the row delete (BOOTSTRAP.md §4).
// Email is the handle, never the identity. Matched case-insensitively against
// the same expression the unique index uses, so a lookup cannot disagree with
// what the index considers a duplicate. Soft-deleted Users are invisible here.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Email,
		&i.DisplayName,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, household_id, email, display_name, locale, time_zone, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HouseholdID,
		&i.Email,
		&i.DisplayName,
		&i.Locale,
		&i.TimeZone,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const recordLoginFailure = `-- name: RecordLoginFailure :exec
INSERT INTO login_attempts (key, failure_count, backoff_until)
VALUES ($1, 1, now() + $2::interval)
ON CONFLICT (key) DO UPDATE SET
    failure_count = login_attempts.failure_count + 1,
    -- Exponential, capped: 2^n seconds from the first failure, never longer
    -- than the cap. Backoff, never a hard lockout.
    backoff_until = now() + least(
        $2::interval * pow(2, login_attempts.failure_count),
        $3::interval
    ),
    updated_at = now()
`

type RecordLoginFailureParams struct {
	Key          string
	FirstBackoff pgtype.Interval
	MaxBackoff   pgtype.Interval
}

func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) error {
	_, err := q.db.Exec(ctx, recordLoginFailure, arg.Key, arg.FirstBackoff, arg.MaxBackoff)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now(), expires_at = $2
WHERE id = $1
`

type TouchSessionParams struct {
	ID        string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.ExpiresAt)
	return err
}

const upsertCredential = `-- name: UpsertCredential :exec
INSERT INTO credentials (user_id, password_hash)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET password_hash = EXCLUDED.password_hash, updated_at = now()
`

type UpsertCredentialParams struct {
	UserID       pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) error {
	_, err := q.db.Exec(ctx, upsertCredential, arg.UserID, arg.PasswordHash)
	return err
}
