// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package db

import (
	"context"
)

const ping = `-- name: Ping :one

SELECT 1::int AS ok
`

// Readiness probe for GET /health. A round-trip through the pool proves more
// than pgx's own Ping: it takes a connection from the pool, executes, and scans,
// which is the path every real query takes. A pool that is exhausted or pointed
// at a database the role cannot read fails here and passes a bare Ping.
func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
