// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

type Credential struct {
	UserID       pgtype.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Household struct {
	ID                    pgtype.UUID
	DisplayName           string
	ReportingCurrency     string
	PeriodStartDay        int32
	DayStartsAt           pgtype.Time
	ExpectedMonthlyIncome decimal.NullDecimal
	AllowanceMode         string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
}

type Invitation struct {
	ID           pgtype.UUID
	HouseholdID  pgtype.UUID
	InvitedEmail string
	TokenHash    string
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	AcceptedAt   pgtype.Timestamptz
}

type LoginAttempt struct {
	Key          string
	FailureCount int32
	BackoffUntil pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Session struct {
	ID         string
	UserID     pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
	UserAgent  *string
}

type User struct {
	ID          pgtype.UUID
	HouseholdID pgtype.UUID
	Email       string
	DisplayName string
	Locale      string
	TimeZone    string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}
