// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Readiness probe for GET /health. A round-trip through the pool proves more
	// than pgx's own Ping: it takes a connection from the pool, executes, and scans,
	// which is the path every real query takes. A pool that is exhausted or pointed
	// at a database the role cannot read fails here and passes a bare Ping.
	Ping(ctx context.Context) (int32, error)
}

var _ Querier = (*Queries)(nil)
